### ISSUE TITLE
Crash on Linux/RADV at startup

### ISSUE THREAD

**Issue by kwahoo2** [geefr/vsgvr#1]
Hello,

I realize that the project is at very early development stage, it is quite interesting for me already. Unfortunately it crashes at startup for me. There are outputs with Vulkan validation layers:

https://gist.github.com/kwahoo2/4d23b4a4b5ba4e2e4b184a05d55686bc
https://gist.github.com/kwahoo2/bddd491eb2ed576f74c03d25450ffd9d

I saw VUID-VkSubpassDescription-pDepthStencilAttachment-02650(ERROR / SPEC): earlier in vsgviewer https://github.com/vsg-dev/MyFirstVsgApplication/issues/5
But there is also 
```
VUID-vkBindImageMemory-image-01044(ERROR / SPEC): msgNum: 1866378390 - Validation Error: [ VUID-vkBindImageMemory-image-01044 ] Object 0: handle = 0xe7e6d0000000000f, type = VK_OBJECT_TYPE_DEVICE_MEMORY; Object 1: handle = 0xcb3ee80000000007, type = VK_OBJECT_TYPE_IMAGE; Object 2: handle = 0xead9370000000008, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x6f3eac96 | In vkBindImageMemory(), attempting to bind VkDeviceMemory 0xe7e6d0000000000f[] to VkImage 0xcb3ee80000000007[] which has already been bound to VkDeviceMemory 0xead9370000000008[]. The Vulkan spec states: image must not already be backed by a memory object (https://vulkan.lunarg.com/doc/view/1.2.176.1/linux/1.2-extensions/vkspec.html#VUID-vkBindImageMemory-image-01044)
```

SteamVR info:
```
SteamVR Version 1.14.16 (1600466902)
Steam:	Public (linux_v1.14)
Tracking:	lighthouse
OS:	Linux version 5.11.0-17-generic (buildd@lcy01-amd64-002) (gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, GNU ld (GNU Binutils for Ubuntu) 2.36.1) #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 (0.0.0.0)
Direct Mode Graphics:	AMD (80097379)

System
Admin:	Yes
Async Reprojection:	Enabled
Performance drops:	24/1 7/2 4/3 1/4 840/2098
User IPD (m):	0.0634387

Displays - Direct Mode
```

**Comment by geefr** [comment]
Hey thanks for the report - Good to gather these for later at least.
Current status is that I've messed up the matrices/exactly what is being rendered to the headset, but the basic connection / displaying <something> should work.

I don't have any amd cards myself (not new ones at least), so not too surprised by this kind of thing. If the crash only happens in my code then I'd bet it's related to how I'm making the images - I threw that bit together in a few minutes, a long time ago, and it's definitely not an optimal approach.

Probably best to wait until the depth issues are resolved without openvr first, and maybe in that time I'll have found some time to work on the vr specific issues.

**Comment by kwahoo2** [comment]
Thank you for the answer. 

No need to hurry, I have to get correct vsg rendering on flat screen first.
I am not surprised that you have some issues with matrices, etc. I found OpenVR docs lacking (WaitGetPoses is a mystery for many) and sometimes plainly wrong (eg. top and bottom planes in GetProjectionRaw are swapped...)

Do you have plans to make an OpenXR implementation still? 
I found that getting XR support directly needs a lot more coding than OpenVR, but https://github.com/KhronosGroup/OpenXR-Hpp helps a lot.  In exchange there are better docs, more supported platforms, action sets (for controllers), more explicit control and validation layers (haven't tested). That's my observation as hobbyist, not a pro programmer.

**Comment by geefr** [comment]
Yeah, think I know what's wrong (I'm swapping axes for position components, but not orientation). My WaitGetPoses isn't optimal but fast enough (Pulled it from an engine I wrote a while back, hit some fun bugs with openvr..)

Haven't looked at OpenXR much yet, but yes eventually. The plan for now is just to get a functional prototype, then face the question of nice vsg integration (Say vsg::VRViewer(someRuntimeContext);).
For other runtimes/headsets though it's similar concepts (I hope) - A render to texture for presentation, pose updates and space transformations etc.

**Comment by kwahoo2** [comment]
Small update:
Upgraded to SteamVR 1.17.12 and now the example does not crash, but freezes PC, generating artifacts on the main monitor.
Here is the -d log:
[example_vr.log](https://github.com/geefr/vsg-vr-prototype/files/6602830/example_vr.log)
This looks interesting:
```
VUID-vkAcquireNextImageKHR-swapchain-01802(ERROR / SPEC): msgNum: 1050126472 - Validation Error: [ VUID-vkAcquireNextImageKHR-swapchain-01802 ] Object 0: handle = 0xa182620000000079, type = VK_OBJECT_TYPE_SWAPCHAIN_KHR; | MessageID = 0x3e97a888 | vkAcquireNextImageKHR: Application has already previously acquired 1 image from swapchain. Only 1 is available to be acquired using a timeout of UINT64_MAX (given the swapchain has 3, and VkSurfaceCapabilitiesKHR::minImageCount is 3). The Vulkan spec states: If the number of currently acquired images is greater than the difference between the number of images in swapchain and the value of VkSurfaceCapabilitiesKHR::minImageCount as returned by a call to vkGetPhysicalDeviceSurfaceCapabilities2KHR with the surface used to create swapchain, timeout must not be UINT64_MAX (https://vulkan.lunarg.com/doc/view/1.2.176.1/linux/1.2-extensions/vkspec.html#VUID-vkAcquireNextImageKHR-swapchain-01802)
```

![20210605_180145](https://user-images.githubusercontent.com/3474114/120898053-92930700-c629-11eb-96b4-e0b47c04a05f.jpg)

If I remove hmdCommandGraph, the mirror window works fine, including tracking
```
  //viewer->assignRecordAndSubmitTaskAndPresentation({hmdCommandGraph, desktopCommandGraph});
  viewer->assignRecordAndSubmitTaskAndPresentation({desktopCommandGraph});
```

**Comment by geefr** [comment]
Thanks for testing, yes that's very interesting..

The thing to work out would be whether it's coming from vsg, or the vulkan bits of the openvr runtime. I did have a similar error before, but the vr view isn't using a swapchain (just temporary images for rendering, handed to openvr, which does its own thing for presentation).

Can you try putting the command graph back in, but comment out the call to vr->submitFrames.
That should highlight if it's something in vsg / my image setup, or something invalid being passed to openvr (Or an internal openvr bug...runs well on linux but there's frequent issues for me..)

**Comment by kwahoo2** [comment]
Done.
Still freezes the PC, log does not contain swapchain error now, just VUID-vkBindImageMemory-image-01044
[example_vr2.log](https://github.com/geefr/vsg-vr-prototype/files/6602971/example_vr2.log)

**Comment by kwahoo2** [comment]
I am happy to report that current vsgvr release works perfectly fine with RADV! 
(SteamVR 1.18.6)
